package bluelab.connect.ui.b.a;

import bluelab.connect.c.Enum_ControlType;
import bluelab.connect.c.BluelabRemoteXbeeDevice;
import bluelab.connect.model.SettingFileModel;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.border.EmptyBorder;

public final class f extends a {
   private JLabel f;
   private JLabel g;
   private JLabel h;
   private JLabel i;
   private JLabel j;
   private JLabel k;
   private JLabel l;
   private JLabel m;
   private JLabel n;
   private JLabel o;
   private JLabel p;
   private JLabel q;
   private JLabel r;
   private JLabel s;
   private JLabel t;

   public f(BluelabRemoteXbeeDevice dev, SettingFileModel var2) {
      this.device = dev;
      this.settingFileModel = var2;
      this.setOpaque(false);
      this.setBorder(new EmptyBorder(15, 10, 10, 10));
      this.setLayout(new BorderLayout(0, 0));
      JPanel var4;
      (var4 = new JPanel(new BorderLayout(0, 0))).setOpaque(false);
      var4.setLayout(new GridBagLayout());
      this.add(var4, "North");
      GridBagConstraints var5;
      (var5 = new GridBagConstraints()).gridx = -1;
      var5.gridy = 0;
      var5.fill = 2;
      var5.insets = new Insets(10, 10, 10, 10);
      var5.weightx = 1.0D;
      JLabel var3 = new JLabel("Actual");
      var4.add(var3, var5);
      this.f = new JLabel("");
      this.f.setFont(c);
      this.f.setHorizontalAlignment(0);
      var4.add(this.f, var5);
      this.k = new JLabel("");
      this.k.setFont(c);
      this.k.setHorizontalAlignment(0);
      var4.add(this.k, var5);
      this.p = new JLabel("");
      this.p.setFont(c);
      this.p.setHorizontalAlignment(0);
      var4.add(this.p, var5);
      var5.gridy = 1;
      var3 = new JLabel("Required");
      var4.add(var3, var5);
      this.g = new JLabel("");
      this.g.setFont(d);
      this.g.setHorizontalAlignment(0);
      var4.add(this.g, var5);
      this.l = new JLabel("");
      this.l.setFont(d);
      this.l.setHorizontalAlignment(0);
      var4.add(this.l, var5);
      this.q = new JLabel("");
      this.q.setFont(d);
      this.q.setHorizontalAlignment(0);
      var4.add(this.q, var5);
      var5.gridy = 2;
      var5.gridwidth = 0;
      var4.add(new JSeparator(0), var5);
      var5.gridwidth = 1;
      var5.gridy = 3;
      var3 = new JLabel("Today's dose count");
      var4.add(var3, var5);
      this.h = new JLabel("");
      this.h.setFont(e);
      this.h.setHorizontalAlignment(0);
      var4.add(this.h, var5);
      this.m = new JLabel("");
      this.m.setFont(e);
      this.m.setHorizontalAlignment(0);
      var4.add(this.m, var5);
      this.r = new JLabel("");
      this.r.setFont(e);
      this.r.setHorizontalAlignment(0);
      var4.add(this.r, var5);
      var5.gridy = 4;
      var3 = new JLabel("Today's dose time");
      var4.add(var3, var5);
      this.i = new JLabel("");
      this.i.setFont(e);
      this.i.setHorizontalAlignment(0);
      var4.add(this.i, var5);
      this.n = new JLabel("");
      this.n.setFont(e);
      this.n.setHorizontalAlignment(0);
      var4.add(this.n, var5);
      this.s = new JLabel("");
      this.s.setFont(e);
      this.s.setHorizontalAlignment(0);
      var4.add(this.s, var5);
      var5.gridy = 5;
      var3 = new JLabel("Control direction");
      var4.add(var3, var5);
      this.j = new JLabel("");
      this.j.setFont(e);
      this.j.setHorizontalAlignment(0);
      var4.add(this.j, var5);
      this.o = new JLabel("");
      this.o.setFont(e);
      this.o.setHorizontalAlignment(0);
      var4.add(this.o, var5);
      this.t = new JLabel("");
      this.t.setFont(e);
      this.t.setHorizontalAlignment(0);
      var4.add(this.t, var5);
      var5.gridy = 6;
      var5.gridwidth = 0;
      var4.add(this.b(), var5);
      this.a();
   }

   public final void a() {
      this.a(this.f, Enum_ControlType.CONDUCTIVITY);
      this.a(this.g, this.h, this.i, this.j, Enum_ControlType.CONDUCTIVITY);
      this.a(this.k, Enum_ControlType.PH);
      this.a(this.l, this.m, this.n, this.o, Enum_ControlType.PH);
      this.a(this.p, Enum_ControlType.TEMPERATURE);
      this.a(this.q, this.r, this.s, this.t, Enum_ControlType.TEMPERATURE);
   }
}